package com.example.demo.model;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

@Document(collection = "tireRequests")
public class TireRequest {

    @Id
    private String id; // Auto-generated by MongoDB

    private String vehicleNo;
    private String vehicleType;
    private String vehicleBrand;
    private String vehicleModel;
    private String userSection;
    private Date replacementDate;
    private String existingMake;
    private String tireSize;
    private Integer noOfTires;
    private Integer noOfTubes;
    private String costCenter;
    private Integer presentKm;
    private Integer previousKm;
    private String wearIndicator; // "No", "Yes"
    private String wearPattern; // "One Edge", "Center"
    private String officerServiceNo; // Employee ID of the requesting officer
    private String comments;
    private List<String> imagePaths = new ArrayList<>(); // Initialize to avoid nulls
    private String status; // "Pending", "Approved", "Rejected"
    private Date requestDate;
    private Date approvedDate;
    private Date rejectedDate;
    private String approvedBy; // Employee ID of the approver

    // Default constructor
    public TireRequest() {
        this.requestDate = new Date(); // Auto-generate request date
        this.status = "Pending";
    }

    // Constructor with essential fields
    public TireRequest(String vehicleNo, String vehicleType, String vehicleBrand, String vehicleModel,
                       String userSection, Date replacementDate, String existingMake, String tireSize,
                       Integer noOfTires, Integer noOfTubes, String costCenter, Integer presentKm,
                       Integer previousKm, String wearIndicator, String wearPattern, String officerServiceNo,
                       String comments) {
        this.vehicleNo = vehicleNo;
        this.vehicleType = vehicleType;
        this.vehicleBrand = vehicleBrand;
        this.vehicleModel = vehicleModel;
        this.userSection = userSection;
        this.replacementDate = replacementDate;
        this.existingMake = existingMake;
        this.tireSize = tireSize;
        this.noOfTires = noOfTires;
        this.noOfTubes = noOfTubes;
        this.costCenter = costCenter;
        this.presentKm = presentKm;
        this.previousKm = previousKm;
        this.wearIndicator = wearIndicator;
        this.wearPattern = wearPattern;
        this.officerServiceNo = officerServiceNo;
        this.comments = comments;
        this.status = "Pending"; 
        this.requestDate = new Date(); 
    }

    // Getters and Setters

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getVehicleNo() {
        return vehicleNo;
    }

    public void setVehicleNo(String vehicleNo) {
        this.vehicleNo = vehicleNo;
    }

    public String getVehicleType() {
        return vehicleType;
    }

    public void setVehicleType(String vehicleType) {
        this.vehicleType = vehicleType;
    }

    public String getVehicleBrand() {
        return vehicleBrand;
    }

    public void setVehicleBrand(String vehicleBrand) {
        this.vehicleBrand = vehicleBrand;
    }

    public String getVehicleModel() {
        return vehicleModel;
    }

    public void setVehicleModel(String vehicleModel) {
        this.vehicleModel = vehicleModel;
    }

    public String getUserSection() {
        return userSection;
    }

    public void setUserSection(String userSection) {
        this.userSection = userSection;
    }

    public Date getReplacementDate() {
        return replacementDate;
    }

    public void setReplacementDate(Date replacementDate) {
        this.replacementDate = replacementDate;
    }

    public String getExistingMake() {
        return existingMake;
    }

    public void setExistingMake(String existingMake) {
        this.existingMake = existingMake;
    }

    public String getTireSize() {
        return tireSize;
    }

    public void setTireSize(String tireSize) {
        this.tireSize = tireSize;
    }

    public Integer getNoOfTires() {
        return noOfTires;
    }

    public void setNoOfTires(Integer noOfTires) {
        this.noOfTires = noOfTires;
    }

    public Integer getNoOfTubes() {
        return noOfTubes;
    }

    public void setNoOfTubes(Integer noOfTubes) {
        this.noOfTubes = noOfTubes;
    }

    public String getCostCenter() {
        return costCenter;
    }

    public void setCostCenter(String costCenter) {
        this.costCenter = costCenter;
    }

    public Integer getPresentKm() {
        return presentKm;
    }

    public void setPresentKm(Integer presentKm) {
        this.presentKm = presentKm;
    }

    public Integer getPreviousKm() {
        return previousKm;
    }

    public void setPreviousKm(Integer previousKm) {
        this.previousKm = previousKm;
    }

    public String getWearIndicator() {
        return wearIndicator;
    }

    public void setWearIndicator(String wearIndicator) {
        this.wearIndicator = wearIndicator;
    }

    public String getWearPattern() {
        return wearPattern;
    }

    public void setWearPattern(String wearPattern) {
        this.wearPattern = wearPattern;
    }

    public String getOfficerServiceNo() {
        return officerServiceNo;
    }

    public void setOfficerServiceNo(String officerServiceNo) {
        this.officerServiceNo = officerServiceNo;
    }

    public String getComments() {
        return comments;
    }

    public void setComments(String comments) {
        this.comments = comments;
    }

    public List<String> getImagePaths() {
        return imagePaths;
    }

    public void setImagePaths(List<String> imagePaths) {
        this.imagePaths = imagePaths;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public Date getRequestDate() {
        return requestDate;
    }

    public void setRequestDate(Date requestDate) {
        this.requestDate = requestDate;
    }

    public Date getApprovedDate() {
        return approvedDate;
    }

    public void setApprovedDate(Date approvedDate) {
        this.approvedDate = approvedDate;
    }

    public Date getRejectedDate() {
        return rejectedDate;
    }

    public void setRejectedDate(Date rejectedDate) {
        this.rejectedDate = rejectedDate;
    }

    public String getApprovedBy() {
        return approvedBy;
    }

    public void setApprovedBy(String approvedBy) {
        this.approvedBy = approvedBy;
    }

    @Override
    public String toString() {
        return "TireRequest{" +
                "id='" + id + '\'' +
                ", vehicleNo='" + vehicleNo + '\'' +
                ", status='" + status + '\'' +
                // ... other fields ...
                '}';
    }
}
